trading_cards/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', DefaultFormsetView.as_view(), name="home"),
    path('privacy', PrivacyView.as_view(), name="privacy"),
    path('impressum', ImpressumView.as_view(), name="impressum"),
    path('admin/', admin.site.urls),
]

trading_cards/forms.py
from django import forms
from django.forms import Form
from .models import *
from io import BytesIO
from django.core.exceptions import ValidationError
import tempfile
from django.core.validators import RegexValidator, MinLengthValidator, MaxLengthValidator

TEAM_CHOICES = (("25_Rare", "Rare"),
                ("24_Ref", "Referee"),
                ("23_Snitch", "Snitch"),
                ("22_Volunteer", "Volunteer"),
                ("21_Committee", "Committee"),
                ("04_Austria", "Austria"),
                ("18_Belgium", "Belgium"),
                ("05_Catalonia", "Catalonia"),
                ("06_Czech", "Czech Republic"),
                ("19_Denmark", "Denmark"),
                ("07_Finland", "Finland"),
                ("03_France", "France"),
                ("02_Germany", "Germany"),
                ("08_Ireland", "Ireland"),
                ("09_Italy", "Italy"),
                ("17_Netherlands", "Netherlands"),
                ("01_Norway", "Norway"),
                ("10_Poland", "Poland"),
                ("16_Scotland", "Scotland"),
                ("20_Slovakia", "Slovakia"),
                ("11_Slovenia", "Slovenia"),
                ("12_Spain", "Spain"),
                ("13_Switzerland", "Switzerland"),
                ("14_Turkey", "Turkey"),
                ("15_UK", "UK"))

POSITION_CHOICES = (("Keeper", "Keeper"),
                    ("Chaser", "Chaser"),
                    ("Beater", "Beater"),
                    ("Seeker", "Seeker"),
                    ("Utility", "Utility"),
                    ("Speaking Captain", "Speaking Captain"),
                    ("Coach", "Coach"),
                    ("Team Captain", "Team Captain"),
                    ("Head Referee", "Head Referee"),
                    ("Assistant Referee", "Assistant Referee"),
                    ("Snitch Referee", "Snitch Referee"),
                    ("Snitch Runner", "Snitch Runner"),
                    ("Pitch Manager", "Pitch Manager"),
                    ("Merchandise", "Merchandise"),
                    ("Live Steam", "Live Stream"),
                    ("Commentator", "Commentator"),
                    ("Committee", "Committee"),
                    ("Volunteer", "Volunteer"),
                    ("Kidditch Coach", "Kidditch Coach"),
                   )


class ImageDataField(forms.ImageField):
    def to_python(self, data):
        from base64 import b64decode
        if not data:
            raise ValidationError(self.error_messages['invalid_image'])
        f = tempfile.NamedTemporaryFile(suffix=".png")
        try:
            f.write(b64decode(data.split(',')[1]))
        except IndexError:
            raise ValidationError(self.error_messages['invalid_image'])
        from PIL import Image

        try:
            # load() could spot a truncated JPEG, but it loads the entire
            # image in memory, which is a DoS vector. See #3848 and #18520.
            image = Image.open(f)
            # verify() must be called immediately after the constructor.
            image.verify()

            # Annotating so subclasses can reuse it for their own validation
            f.image = image
            # Pillow doesn't detect the MIME type of all formats. In those
            # cases, content_type will be None.
            f.content_type = Image.MIME.get(image.format)
        except Exception as exc:
            # Pillow doesn't recognize it as an image.
            raise ValidationError(
                self.error_messages['invalid_image'],
                code='invalid_image',
            ) from exc
        if hasattr(f, 'seek') and callable(f.seek):
            f.seek(0)
        return f


class CardForm(Form):
    name = forms.CharField(label='Your name', max_length=30, help_text="Recommend below 20 characters")
    team = forms.ChoiceField(choices=TEAM_CHOICES)
    number = forms.CharField(label='Your number', max_length=2, required=False, validators=[
            RegexValidator(
                r'^[0-9]*$',
                'Only 0-9 and 00-99 are allowed.',
                'Invalid Number'
            ),
            MinLengthValidator(1),
            MaxLengthValidator(2),
        ],)
    phrase = forms.CharField(label='Phrase (optional)', widget=forms.Textarea, max_length=100, help_text="Recommend below 70 characters", required=False)
    copy = forms.CharField(label='Copyright', help_text='Give credit, if the photographer wants it.', max_length=50, required=False)
    position = forms.MultipleChoiceField(choices=POSITION_CHOICES, help_text='See if multiple positions fit, otherwise maybe chose Utility or drop less important ones; choose multiple by holding Ctrl.')
    # func = forms.MultipleChoiceField(choices=FUNCTION_CHOICES, required=False,
    #                                      help_text='Max. 3 functions; choose multiple by holding Ctrl./Strg.')
    cata = forms.IntegerField(label='Kilometers traveled to Bamberg', min_value=0, max_value=9999, required=False)
    catb = forms.IntegerField(label='Sunburn Resistance (0-10)', min_value=-5, max_value=20, required=False)
    catc = forms.IntegerField(label='Traded Jerseys', min_value=0, max_value=999, required=False)
    catd = forms.IntegerField(label='Years of Quidditch', min_value=0, max_value=20, required=False)
    image = ImageDataField(widget=forms.HiddenInput)

templates/base.html
{% extends 'bootstrap.html' %}

{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block bootstrap4_content %}

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">{% block title %}(no title){% endblock %}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Generator</a>
              </li>
              <li class="nav-item">
               <a class="nav-link" href="{% url 'privacy' %}">Privacy Policy</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'impressum' %}">Impressum</a>
              </li>
            </ul>
          </div>
        </nav>
    <div class="container">
        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}


{% block bootstrap4_extra_head %}
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#550055">
    <meta name="apple-mobile-web-app-title" content="Trading Card Generator">
    <meta name="application-name" content="Trading Card Generator">
    <meta name="msapplication-TileColor" content="#00aba9">
    <meta name="theme-color" content="#ffffff">
    {% block extra_head %}{% endblock %}
{% endblock %}

templates/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

templates/cardform.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% load staticfiles %}

{% block title %}
    Trading Card Generator
{% endblock %}

{% block extra_head %}
    {{ form.media }}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'cropperjs/dist/cropper.css' %}">
    <link rel="stylesheet" href="{% static 'cardform.css' %}">

{% endblock %}

{% block content %}
    {% bootstrap_form_errors form %}
    <label class="control-label" for="id_name">Picture</label>
      <div class="container">
        <div class="control-group error">
            <label class="label">
              <img class="rounded" data-toggle="tooltip" title="Upload your image" id="avatar" src="{% static 'Upload.jpg' %}" alt="avatar" style="width: 25%; height: 25%">
              <input type="file" class="sr-only" id="input" name="image" accept="image/*">
            </label>
            {% for error in form.image.errors %}
                <span class="help-inline errorlist errors">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="alert" role="alert" style="display: none;"></div>
        <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Crop the image</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="img-container">
                  <img id="image" src="">
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="crop">Crop</button>
              </div>
            </div>
          </div>
        </div>
    </div>
    <script src="{% static 'cropperjs/dist/cropper.js' %}"></script>
    <script src="{% static 'cardform.js' %}"></script>
    <script src="{% static 'hermite-resize/dist/hermite.js' %}"></script>
    <div class="help-block">To upload a picture, click on the image above.<br>
        The trading card will be cropped in the production process. Please keep all important details off the edges of the card.<br>
        If you're satisfied with your card, please upload it <a href="https://goo.gl/forms/JIPkvU8XdYYGFBfH2">here</a>.<br>
    </div>
    <form role="form" id="cropping_form" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form %}
        <div class="help-block">Press the submit button to start the generation of the trading card. The upload of the image might take a few seconds. Thank you for your patience.<br>
            <strong>If you're satisfied with your card, please upload it <a href="https://goo.gl/forms/JIPkvU8XdYYGFBfH2">here</a></strong>. The card and your data is not saved on this server!</div>
        {% buttons submit='Submit' %}{% endbuttons %}

    </form>
{% endblock %}